### sign in
# @name signin
POST http://localhost:3009/auth/signin
Content-Type: application/json

{
	"username": "superman",
	"password": "supermannofly"
}

@token={{signin.response.body.token}}

### get user by id
GET http://localhost:3009/users/1
Authorization: Bearer {{token}}

### get user by id, but user not found
GET http://localhost:3009/users/999
Authorization: Bearer {{token}}

### get all users
GET http://localhost:3009/users?limit=10&offset=0
Authorization: Bearer {{token}}

### user itself update user by id
PATCH http://localhost:3009/users/8
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"username": "JohnDoe11111",
	"password": "123456"
}

### admin update user role by id
PATCH http://localhost:3009/users/9
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"roles": [
		{
			"id": 1,
			"name": "User"
		},
		{
			"id": 2,
			"name": "Moderator"
		}
	]
}

### moderator update user permissions by id
PATCH http://localhost:3009/users/9
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"permissions": [
		{
			"id": 1,
			"name": "READ"
		},
		{
			"id": 2,
			"name": "WRITE"
		},
		{
			"id": 3,
			"name": "DELETE"
		}
	]
}

### delete user by id
DELETE http://localhost:3009/users/8
Authorization: Bearer {{token}}
